---

- hosts: all
  become: true
  tasks:

  - name: install php and  awpache2 packages
    ansible.builtin.apt:
      name:
        - apache2
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install php and httpd packages
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install php and apache2 packages
    ansible.builtin.zypper:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Suse"

